import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Jobify App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body
        >           
          <Providers>
          {children}
            </Providers>
        </body>
      </html>
    </ClerkProvider>

  );
}
